### ISSUE TITLE
Add support for Beacons

### ISSUE THREAD

**Issue by 19wolf** [Kakyo/FactorioCalculator#1]

**Comment by Kakyo** [comment]
you can already do this. 
Let's say you place a beacon with 2 speed3 mods, this is the same thing as adding 1 speed3 directly in the building.
Also, the calculator supports decimal numbers in the module, so as the beacon provides only half the effect of the module, you can add 0.5 module to the calculator.

Another example, if you want to achieve a very specific number and you need 4 prod3 directly in the building, 2speed3 in one beacon and 1speed3 + 1speed2 in another beacon, you can setup the values as ( 4 speed3 + 1.5speed3 + 0.5speed2 )
