### ISSUE TITLE
0.15.10 Upate required

### ISSUE THREAD

**Issue by Neodark7** [Kakyo/FactorioCalculator#2]
Hello awesome tool here ! but has some recipes changed between 0.15.2 and 0.15.10 can you update this please ? :D

**Comment by Kakyo** [comment]
Ooookay, updated. Got completely distracted playing and forgot to update the calc. haha

You might need to clear your browser cache to see the latest changes =)

**Comment by Neodark7** [comment]
72 hours in the last 15 days for me so don't worry i understand you. =D
Thanks a lot for the quick update go back to your factory now ! :D
