### ISSUE TITLE
Disable productivity modules for Intermediate Products

### ISSUE THREAD

**Issue by Neodark7** [Kakyo/FactorioCalculator#3]
I was doing some maths for my "1k of every science packs every minute" goal :D and f***** the numbers with things like that :D http://i.imgur.com/4FNNAh7.png can you do something ? =3

(Edit, if you wanna check :P https://pastebin.com/wYL4GDtc )

**Comment by Kakyo** [comment]
This is already in my todo list, and i might try to do it next (right after all recipe issues are fixed). It's being requested a lot.

so, give me a week or so and maybe I add it. I just want to do something automated (like recipe extraction), otherwise it can be troublesome to work with the experimental branch

**Comment by Kakyo** [comment]
I just updated the calc with a flag to disable the productivity input of non-intermediate recipes (there's a small issue where it'll not clear if already set, looking into it).

But I don't get your complain in this one. If you want 1 furnace/minute, than you need 0,01 assemblies with 8x speed3 in it. The other way around 1 assembly full time will output 75 furnaces/minute with the same 8x speed3 (i removed the productivity for those numbers)

**Comment by Neodark7** [comment]
yaay, i think you should also put an automatic cap for production modules, i mean if i select the iron plates recipe, using the electric furnace, i should not be able to put more than 2 production modules, same with the stone furnace, i should not be able to put them at all =D

**Comment by Kakyo** [comment]
Well, if i'm going to reset it, might as well be to any value instead of forcefully set to 0. 

So as soon as i'm able to fix this reset part, i'll take a look into capping it. (at work now, can't do anything =/ ). I believe that up to Wednesday i can fix this, if not sooner

**Comment by Neodark7** [comment]
it's not really a big deal/issue, i have all the machine modules limits in mind, but yeah i use your tool a lot so i think it's a big plus ^^

**Comment by Neodark7** [comment]
seems to be done, right ? i close this then :D
