### ISSUE TITLE
Missing dependencies in package.json

### ISSUE THREAD

**Issue by MarekBeseda** [Kakyo/FactorioCalculator#4]
There are some dependencies that are missing from package.json. For example babelcore. I am trying to fork, but i'm having trouble doing so as I can't run it on my local machine as you are not using the latest versions.

**Comment by Kakyo** [comment]
i never needed babel (for several projects), so could you give me more info on what's happening ?

Also I would *really* like to avoid bloating this small project with a billion and a half dependencies, feels like this : https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f

**Comment by MarekBeseda** [comment]
So why is babel used in gulpfile? Is it some unnecessary dependency?

On Mon, 15 May 2017 13:56 Kakyo, <notifications@github.com<mailto:notifications@github.com>> wrote:

i never needed babel (for several projects), so could you give me more info on what's happening ?

Also I would really like to avoid bloating this small project with a billion and a half dependencies, feels like this : https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f

**Comment by Kakyo** [comment]
Well, i literally just installed knockout and assumed that it was all necessary for it. Only now i see the "gulp-babel" in packages.json.

i'll try to work it out, i do want to fix some tech debts in this project ( like no tests! insanity! ) But i'll need some time. If you want/need to update the current stack, feel free to do it.

Also, ignore the "reference" above. This issues has noting to due with the pr.
